name: Follower Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # every hour

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      ROCKET_API_TOKEN: ${{ secrets.ROCKET_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python main.py
